# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'weLearnOAuth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weLearnOAuth
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'SnapKit'
  pod 'GoogleSignIn'

end


